# Docs: https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 1 * * 6"
      timezone: "Etc/UTC"
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 1 * * 6"
      timezone: "Etc/UTC"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "cron"
      cronjob: "0 1 * * 6"
      timezone: "Etc/UTC"
