[project]
name = "shrubbery"
description = "shrubbery"
version = "0.0.0"
authors = [
    { name = "altermarkive", email = "altermarkive@users.noreply.github.com" }
]
readme = "README.md"
requires-python = ">=3.13"
license = {text = "GNU General Public License v3.0"}
classifiers = [
    "Programming Language :: Python :: 3",
]
dependencies = [
    "amltk>=1.12.1",
    "autokeras>=2.0.0",
    "autoviml>=0.1.710",
    "cudf-cu13>=25.10.0",
    "cuml-cu13>=25.10.0",
    "gama>=23.0.0",
    "hydra-core>=1.3.2",
    "keras>=3.11.1",
    "keras-tuner",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.5",
    "minisom>=2.3.5",
    # File "/usr/local/lib/python3.13/dist-packages/myfm/__init__.py", line 8, in <module>
    #     from ._myfm import RelationBlock
    # ModuleNotFoundError: No module named 'myfm._myfm'
    "myfm==0.3.2.0",
    "numerapi>=2.20.7",
    "numerblox>=1.6.1",
    "plotly>=6.2.0",
    "pyarrow>=19.0.1",
    "scikit-network>=0.33.3",
    "sklearn-genetic>=0.6.0",
    "sklearn-genetic-opt>=0.12.0",
    "skorch>=1.3.0",
    "tabulate>=0.9.0",
    "torch>=2.8.0",
    "tpot>=1.1.0",
    "wandb>=0.21.0",
]

[project.scripts]
shrubbery = "shrubbery:main.main"

[project.optional-dependencies]
dev = [
    "mypy>=1.17.1",
    "pdbpp>=0.11.7", # Extension of Python debugger
    "ruff>=0.12.11",
    "types-requests>=2.32.4.20250809",
    "wat>=0.7.0", # Deep inspection of Python objects
]

[tool.uv]
index-strategy = "unsafe-best-match"

[tool.uv.sources]
torch = [
  { index = "pytorch-cu130" },
]
keras-tuner = { git = "https://github.com/keras-team/keras-tuner.git" }

[[tool.uv.index]]
url = "https://pypi.nvidia.com/"

[[tool.uv.index]]
name = "pytorch-cu130"
url = "https://download.pytorch.org/whl/cu130"
explicit = true

[tool.ruff]
line-length = 79

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
ignore_missing_imports = true
